from enum import Enum

class POWER(Enum):
    INVISIBILITY = "INVISIBILITY"
    SUPER_STRENGTH = "SUPER_STRENGTH"
    SUPER_INTELLIGENCE = "SUPER_INTELLIGENCE"
    SUPER_SPEED = "SUPER_SPEED"
    MANIAC = "MANIAC"
    SELF_REGENERATION = "SELF_REGENERATION"
    ELITE_SHOOTER = "ELITE_SHOOTER"
    POISONOUS = "POISONOUS"